export default class PageResource {//数据表类
  number_1?: number;
  number_2?: number;
  number_3?: number;
  number_4?:number;
  number_5?:number;
  number_6?:number
  number_7?:number
  constructor(
    number_1?: number,
    number_2?: number,
    number_3?: number,
    number_4?: number,
    number_5?: number,
    number_6?: number,
    number_7?: number
  ) {
    this.number_1= number_1;
    this.number_2= number_2;
    this.number_3= number_3;
    this.number_4= number_4;
    this.number_5= number_5;
    this.number_6= number_6;
    this.number_7= number_7;
  }
}